### ISSUE TITLE
Touchwiz support? 

### ISSUE THREAD

**Issue by Mihara** [agentdr8/NoMMI#1]
This is a hack I would adore to bits _(I automate call forwarding depending on location, popups really get in the way)_ if it worked on my Touchwiz 5.1.1 rom. 

What kind of information would be required to make it work?

**Comment by agentdr8** [comment]
I would just need your deodexed Phone.apk and ideally a screenshot of what toast/popup you're wanting to make disappear.

**Comment by Mihara** [comment]
I'm aftaid it's called something else this particular time, at least, naively searching for a file named "Phone.apk" produces no results. I think it got renamed to "Telecom.apk" sometime around 5.0, which I did find. _(Last time I've messed with Android development was back when ICS was brand new, and I've forgotten most of that since)_ Cursory inspection of the inside suggests that's it, at least I see the messages I otherwise see in the dialer. This comes from a [customized rom](http://forum.xda-developers.com/note-4/development/rom-wanamlite-clean-odex-xposed-t2923266/) and should be deodexed already. https://dl.dropboxusercontent.com/u/532373/Telecom.zip

And here are the screenshots [of the actual popup](https://cloud.githubusercontent.com/assets/400675/9715547/f0cff076-5569-11e5-8387-b657cca22e8c.jpg) in [either state](https://cloud.githubusercontent.com/assets/400675/9715614/bdefa146-556a-11e5-9f9f-ed418b28695a.jpg).

**Comment by agentdr8** [comment]
It wasn't Telecom.apk, but TeleService.apk (package name is com.android.phone). But based on the decompiled source, it looks as if this module should work just fine with it. Can you provide the Xposed Installer error.log?

**Comment by Mihara** [comment]
To be honest, I was reluctant to try it in the first place, seeing as how Touchwiz is so bent on altering everything, and a non-working Xposed module can cause a bootloop that can be difficult to get out of, since I'm not sure there's a working platform uninstaller script for this particular combination. _(Xposed on Samsung Lollipop devices has a rather convoluted history due to the changes to ART they introduced.)_

But based on your assurance, I installed the AOSP version and yes, it does work. Many thanks! Sorry to have bothered you about this.

**Comment by agentdr8** [comment]
No worries. I've been a TW user in the past, so I'm well aware of how Samsung likes to muck with stuff. 

Glad to hear it's working for you!
